### ISSUE TITLE
Wires disapear when placing boards

### ISSUE THREAD

**Issue by Nano112** [JimmyCushnie/TUNG#8]
![image](https://user-images.githubusercontent.com/35530362/35044862-2e03dd74-fb92-11e7-8c13-e8dc9146f87e.png)
Wires disapear while placing board some boards i wan't able to reproduce the bug

**Comment by pipe01** [comment]
I have experienced this bug too but I haven't been able to reproduce it either.

**Comment by JimmyCushnie** [comment]
Sorry, could you clarify? You mean wires disappear when you place a cloned board?

**Comment by Shaolin-Funk** [comment]
I've been hit by this too. It seems more likely to occur with very large boards. It can happen when placing a board (whether by "move" or "clone") or when loading a save. I made an 8-bit multiplier (posted to the subreddit) which is large enough to trigger the bug somewhat reliably - it happened twice, once when I was moving it and again when I reloaded the save. It doesn't remove all wires, or even a majority, it seems to pick select wires to break. 

If you can provide me with a debug build that logs failed attempts to spawn a wire, I should be able to reproduce it and hopefully the log will help you tracking this one down.

**Comment by Shaolin-Funk** [comment]
OK I might have made a little progress.

I suspected that the bug might be triggering on save load, so I fixed up my circuit (again!), saved it and backed it up. Then I loaded it, confirmed that it was broken again, and immediately saved. Then I compared the "clean" save to the broken one.

I added a few (well, just under 20000) newlines to each file so that diff could compare them in a meaningful way. The vast majority of the differences were tiny variations of the LocalEulerAngles attribute, which I took as rounding error and unlikely to be a cause of the issue. So I told diff to ignore those and see what else there was. For some reason it didn't strip all of them. Not sure why, I probably messed up the regex. I've put the result up on pastebin to take advantage of the syntax highlighting:

https://pastebin.com/uWFxjxAG

It looks like a bunch of CustomDataArray attributes are getting flipped from true to false. I don't know what that field represents, but if it's anything to do with wires then that might point in the general direction of the culprit.

Files:

[Multiplier-clean.tung](https://drive.google.com/open?id=1FxgiORsw-uhP9-9QL4F1peZD2qU0quwW)  
[Multiplier-broken.tung](https://drive.google.com/open?id=1zdF8kOiOKX29BxPtDSZdxdvTuttafxls)  
[diff.txt](https://drive.google.com/open?id=1uB3pOIHG4HURdJd7WaZ-UFkJKOgOijLF) (including all the LocalEulerAngles spam)  
[diff2.txt](https://drive.google.com/open?id=1DSu8rKAK3xekfvtwuiFQNFPuTWJ1YW74) (with most of the spam stripped out)  

Hope that helps.

**Comment by JimmyCushnie** [comment]
I've now grappled with this for several hours with no success.

Your "clean" save loads for me missing a lot of the wires from your post on reddit, did you upload the wrong save by mistake? I have extensive debug tools which tell me when wires break and nothing is logged when I load the save. I replaced all the missing wires based on a visual examination of your post and got the multiplier working. I reloaded the save dozens of times and nothing ever broke, the multiplier continued to work fine. This was true for both my debug build and the official 0.1.4 release.

A big thing for 0.2 is a refactoring all of the code, and for now I'm just hoping this is fixed as a side effect.

**Comment by Shaolin-Funk** [comment]
I'm calling it clean based on a guess that it might be breaking on load rather than on save. I don't actually know for definite that this is the case.

I owe you an apology though, because I didn't realise until now that 0.1.4 was out. I've been using 0.1.3 so this may be fixed in the current version. I'm going to grab the update now and see if I can break it.

**Comment by JimmyCushnie** [comment]
The bug almost definitely occurs on load rather than on save. Thank you, please keep me posted.

**Comment by Shaolin-Funk** [comment]
So, good news and bad news. The good news is that I don't have to feel guilty about wasting your time by not mentioning which version I was playing on. However that's because the bad news is the bug is still extant in 0.1.4.

More good (relatively) news though: I've managed to find a case that triggers the bug 100% of the time, at least on my machine. 

Check out this save:

[Multiplier.zip](https://github.com/Iamsodarncool/TUNG/files/1651267/Multiplier.zip)

The red board on the floor you'll probably recognise as one of my 4-bit adders. Make a clone of it and lay the clone down on the floor next to the original. Quit and reload. Compare the two adders - the original is fine, but a bunch of wires have vanished from the clone.

My original hypothesis that it's related to the size of the component seems to be disproven here, since this is quite a small board. I did wonder if the size of the save itself might be an issue, so I tried deleting everything other than the test board - still breaks, so it's probably not that either.

One other thing I found curious. If you flip the board over you'll see a pattern of inverters making up the AND and XOR gates for the adder. I've never seen any of these wires break. Only the ones on the front break. I use a lot of pegs to route my wiring, so I wonder if that's the issue.

**Comment by JimmyCushnie** [comment]
Thank you so much for all your help. After hours of hunting, I've finally managed to track it down, and it is fixed in v0.1.5.

You were right, by the way, the issue _was_ on save rather than load. The issue turned out to be with through pegs. Under the hood, through pegs are actually two pegs with a wire between them. In the startup routine for through pegs, it gets the first wire of its first peg and makes it unbreakable and unsaveable. Normally, when you're placing through pegs, this properly gets the wire inside of the through peg; however, when cloning a board, the order of the connections is randomized and the through pegs would sometimes apply these effects to the incorrect wire, making them unsaveable.

Again thank you so much for investigating. The save file with consistent breaking behavior was invaluable and saved me so much time in this.

**Comment by Shaolin-Funk** [comment]
That is awesome, congratulations!
